#!/usr/bin/env sh

echo '코드를 커밋하기 전에 컨벤션을 확인하고 있습니다.'

# Check Prettier
echo "코드 스타일을 검사합니다."

yarn prettier:check ||
(
    echo '코드 스타일에 문제가 발견되어 prettier format을 실행합니다.';
    yarn prettier:format;
    git add .;
    echo '코드 스타일이 수정되었습니다.';
    git commit --amend --no-edit;
    echo '커밋이 성공적으로 수정되었습니다.';
)

# Check ESLint
echo 'ESLint를 검사합니다.'

yarn eslint:check ||
(
  echo 'ESLint 에러가 감지되었습니다.'
  false
)

npx lint-staged

echo '검사가 통과되었습니다! ✅ '